### ISSUE TITLE
Unable to receive images on Android 11

### ISSUE THREAD

**Issue by JonasTS6866** [CakeKing64/P5IM-android-10-fix#6]
Sending images works perfectly, but when receiving an image, it crashes the app

**Comment by CakeKing64** [comment]
I'm personally running A11, you sure you got the latest update which directly addresses that bug?

[https://github.com/CakeKing64/P5IM-android-10-fix/releases/download/v2.3-a10-2/v2.3-android-10-p2.apk](https://github.com/CakeKing64/P5IM-android-10-fix/releases/download/v2.3-a10-2/v2.3-android-10-p2.apk)

**Comment by JonasTS6866** [comment]
Hi, Ive got the v2.3-android-10.apk one and I'm unable to receive images at
all and it crashes when it tries to receive an image while I'm using the
app, If you're on Android 11, and can receive images perfectly fine then it
might be my phone or Sim provider causing some issues.

**Comment by CakeKing64** [comment]
If you're using v2.3-android-10.apk and not the latest (**_v2.3-android-10-p2.apk_**) uninstall the former then install the latter and that should fix the issue

If that doesn't work I have another idea that might help

**Comment by JonasTS6866** [comment]
Hi, I've gotten the newer version as you said, yet I'm still unable to
receive images, what is the other idea that you had to try and fix it?

**Comment by JonasTS6866** [comment]
Good news,I've managed to get it working, turns out my friends who were
sending me the images just needed to change one setting and it's worked
now, thank you for your help! :)

**Comment by CakeKing64** [comment]
Glad it worked out, the other idea was to get you to send logs btw

Tho if it had to do with settings there probably was nothin I could've done about it even with the logs (don't have access to the source code)
